# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

# config file for development, DELETE IT IF YOU WANT.

## Base settings ##
# url:  #the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: /
title: 玉皇山脚砍柴人
description: > #this means to ignore newlines until "nav_lists:"
  玉皇山脚砍柴人

nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html

paths:
  base: /
  home: /
  all:  /all.html
  rss:  /feed.xml

## GitHub repository (if the site is hosted by GitHub) ##
repository: yuhuangshan/yuhuangshan.github.io
repository_tree: master

## Language & timezone ##
lang: zh #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: Asia/Shanghai #see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## Author & social ##
author:
  name: 玉皇山脚砍柴人
  email: yuanzhao.xyc@cainiao.com  #your Email address e.g. someone@site.com
  facebook:   #your Facebook username
  twitter:   #your Twitter username
  github: yuhuangshan  #your GitHub username
  googleplus:   #your Google+ username
  weibo:   #your Weibo username
  douban:   #your Douban username
  linkedin:   #your Linkedin username

## Comment system (Disqus) ##
disqus:
  # shortname:  #the Disqus shortname for the site

## Comment system (gitalk) ##
# please refer to https://github.com/gitalk/gitalk for more info.
gitalk:
  clientID: 7a0e3e30486ec42620e5 #Github Application Client ID
  clientSecret: 693c2eafa465118d14bc4af9c5466ddb26f4aa6c #Github Application Client Secret
  repository: yuhuangshan.github.io #Github repo
  owner: yuhuangshan #Github repo owner
  admin:  #Github repo owner and collaborators, only these guys can initialize github issues, IT IS A LIST.
    - yuhuangshan

## Google Analytics ##
# ga_tracking_id:  #Google analytics id for the site

## Reading quantity (LeanCloud) ##

leancloud:
  app_id:  bxOIvmnlQBvNWnSep024pWX1-gzGzoHsz #LeanCloud App id
  app_key: KY3BEAGeC5Nj6qoJ6lBhIfOO #LeanCloud App key
  app_class: yuhuangshan #LeanCloud App class

custom:
  name: yuanzhao

# mathjax: true

## Paginate ##
paginate: 5
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: html # text | html

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

## Plugins ##
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"

## Development ##
isdebug: false